# https://github.com/jasonetco/jasonetco/blob/master/.github/workflows/daily-updates.yml

name: Update Status

on:
  schedule:
    - cron: 55 5 * * * # “At every 05:55.”
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual trigger to run workflow.

jobs:
  updates:
    name: Update Status
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.USER_SCOPE }}
          script: |
            const script = require('.github/workflows/update-status.js')
            console.log(await script({github, context, core}))
